language: node_js
node_js:
  - "12.16.0"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
script: web-ext --api-key ${API_KEY} --api-secret ${API_SECRET}
before_script:
  - yarn lint
  - yarn test
  - yarn build
after_sucess: yarn docs

# safelist
branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token:  ${GITHUB_TOKEN}
  keep_history: true
  target_branch: gh-pages
  local_dir: docs
  on:
    branch: master